CREATE TABLE IF NOT EXISTS zoho_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  app_name VARCHAR(20) NOT NULL,
  encrypted_refresh_token TEXT NOT NULL,
  iv VARCHAR(32) NOT NULL,
  auth_tag VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_zoho_tokens_app_name (app_name)
) ENGINE=InnoDB;
